config/routes.rb
Rails.application.routes.draw do
  resources :list_permissions

  resources :lists

  resources :tasks

  resources :events

  resources :friends

  resources :users

  get 'admin/landing'

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/friend.rb
class Friend < ActiveRecord::Base
end

app/models/list.rb
class List < ActiveRecord::Base
end

app/models/list_permission.rb
class ListPermission < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def landing
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @events = Event.all
    respond_with(@events)
  end

  def show
    respond_with(@event)
  end

  def new
    @event = Event.new
    respond_with(@event)
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
    respond_with(@event)
  end

  def update
    @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:creatorInvCode, :name, :description, :startDate, :startTime, :endDate, :endTime, :private, :everyone, :friends, :family, :work, :school, :personal)
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @friends = Friend.all
    respond_with(@friends)
  end

  def show
    respond_with(@friend)
  end

  def new
    @friend = Friend.new
    respond_with(@friend)
  end

  def edit
  end

  def create
    @friend = Friend.new(friend_params)
    @friend.save
    respond_with(@friend)
  end

  def update
    @friend.update(friend_params)
    respond_with(@friend)
  end

  def destroy
    @friend.destroy
    respond_with(@friend)
  end

  private
    def set_friend
      @friend = Friend.find(params[:id])
    end

    def friend_params
      params.require(:friend).permit(:name, :title, :nickname, :all, :family, :friend, :work, :school, :personal)
    end
end

app/controllers/list_permissions_controller.rb
class ListPermissionsController < ApplicationController
  before_action :set_list_permission, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @list_permissions = ListPermission.all
    respond_with(@list_permissions)
  end

  def show
    respond_with(@list_permission)
  end

  def new
    @list_permission = ListPermission.new
    respond_with(@list_permission)
  end

  def edit
  end

  def create
    @list_permission = ListPermission.new(list_permission_params)
    @list_permission.save
    respond_with(@list_permission)
  end

  def update
    @list_permission.update(list_permission_params)
    respond_with(@list_permission)
  end

  def destroy
    @list_permission.destroy
    respond_with(@list_permission)
  end

  private
    def set_list_permission
      @list_permission = ListPermission.find(params[:id])
    end

    def list_permission_params
      params.require(:list_permission).permit(:listId, :UserId, :permissionType, :shareStatus)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @lists = List.all
    respond_with(@lists)
  end

  def show
    respond_with(@list)
  end

  def new
    @list = List.new
    respond_with(@list)
  end

  def edit
  end

  def create
    @list = List.new(list_params)
    @list.save
    respond_with(@list)
  end

  def update
    @list.update(list_params)
    respond_with(@list)
  end

  def destroy
    @list.destroy
    respond_with(@list)
  end

  private
    def set_list
      @list = List.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:name, :creatorUserID, :numShared)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @tasks = Task.all
    respond_with(@tasks)
  end

  def show
    respond_with(@task)
  end

  def new
    @task = Task.new
    respond_with(@task)
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.save
    respond_with(@task)
  end

  def update
    @task.update(task_params)
    respond_with(@task)
  end

  def destroy
    @task.destroy
    respond_with(@task)
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:title, :description, :hidden, :completed, :whoCompleted, :dateCompleted, :whoCreated, :createPermission, :whoHid, :dateHidden, :whoEdit, :lastEdit)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @users = User.all
    respond_with(@users)
  end

  def show
    respond_with(@user)
  end

  def new
    @user = User.new
    respond_with(@user)
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.save
    respond_with(@user)
  end

  def update
    @user.update(user_params)
    respond_with(@user)
  end

  def destroy
    @user.destroy
    respond_with(@user)
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :title, :inviteCode)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/list_permissions_helper.rb
module ListPermissionsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :creatorInvCode %><br>
    <%= f.text_field :creatorInvCode %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :startDate %><br>
    <%= f.date_select :startDate %>
  </div>
  <div class="field">
    <%= f.label :startTime %><br>
    <%= f.time_select :startTime %>
  </div>
  <div class="field">
    <%= f.label :endDate %><br>
    <%= f.date_select :endDate %>
  </div>
  <div class="field">
    <%= f.label :endTime %><br>
    <%= f.time_select :endTime %>
  </div>
  <div class="field">
    <%= f.label :private %><br>
    <%= f.check_box :private %>
  </div>
  <div class="field">
    <%= f.label :everyone %><br>
    <%= f.check_box :everyone %>
  </div>
  <div class="field">
    <%= f.label :friends %><br>
    <%= f.check_box :friends %>
  </div>
  <div class="field">
    <%= f.label :family %><br>
    <%= f.check_box :family %>
  </div>
  <div class="field">
    <%= f.label :work %><br>
    <%= f.check_box :work %>
  </div>
  <div class="field">
    <%= f.label :school %><br>
    <%= f.check_box :school %>
  </div>
  <div class="field">
    <%= f.label :personal %><br>
    <%= f.check_box :personal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Creatorinvcode</th>
      <th>Name</th>
      <th>Description</th>
      <th>Startdate</th>
      <th>Starttime</th>
      <th>Enddate</th>
      <th>Endtime</th>
      <th>Private</th>
      <th>Everyone</th>
      <th>Friends</th>
      <th>Family</th>
      <th>Work</th>
      <th>School</th>
      <th>Personal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.creatorInvCode %></td>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td><%= event.startDate %></td>
        <td><%= event.startTime %></td>
        <td><%= event.endDate %></td>
        <td><%= event.endTime %></td>
        <td><%= event.private %></td>
        <td><%= event.everyone %></td>
        <td><%= event.friends %></td>
        <td><%= event.family %></td>
        <td><%= event.work %></td>
        <td><%= event.school %></td>
        <td><%= event.personal %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Creatorinvcode:</strong>
  <%= @event.creatorInvCode %>
</p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @event.startDate %>
</p>

<p>
  <strong>Starttime:</strong>
  <%= @event.startTime %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @event.endDate %>
</p>

<p>
  <strong>Endtime:</strong>
  <%= @event.endTime %>
</p>

<p>
  <strong>Private:</strong>
  <%= @event.private %>
</p>

<p>
  <strong>Everyone:</strong>
  <%= @event.everyone %>
</p>

<p>
  <strong>Friends:</strong>
  <%= @event.friends %>
</p>

<p>
  <strong>Family:</strong>
  <%= @event.family %>
</p>

<p>
  <strong>Work:</strong>
  <%= @event.work %>
</p>

<p>
  <strong>School:</strong>
  <%= @event.school %>
</p>

<p>
  <strong>Personal:</strong>
  <%= @event.personal %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/friends/_form.html.erb
<%= form_for(@friend) do |f| %>
  <% if @friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% @friend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :nickname %><br>
    <%= f.text_field :nickname %>
  </div>
  <div class="field">
    <%= f.label :all %><br>
    <%= f.check_box :all %>
  </div>
  <div class="field">
    <%= f.label :family %><br>
    <%= f.check_box :family %>
  </div>
  <div class="field">
    <%= f.label :friend %><br>
    <%= f.check_box :friend %>
  </div>
  <div class="field">
    <%= f.label :work %><br>
    <%= f.check_box :work %>
  </div>
  <div class="field">
    <%= f.label :school %><br>
    <%= f.check_box :school %>
  </div>
  <div class="field">
    <%= f.label :personal %><br>
    <%= f.check_box :personal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render 'form' %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<h1>Listing friends</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Nickname</th>
      <th>All</th>
      <th>Family</th>
      <th>Friend</th>
      <th>Work</th>
      <th>School</th>
      <th>Personal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.name %></td>
        <td><%= friend.title %></td>
        <td><%= friend.nickname %></td>
        <td><%= friend.all %></td>
        <td><%= friend.family %></td>
        <td><%= friend.friend %></td>
        <td><%= friend.work %></td>
        <td><%= friend.school %></td>
        <td><%= friend.personal %></td>
        <td><%= link_to 'Show', friend %></td>
        <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
        <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path %>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render 'form' %>

<%= link_to 'Back', friends_path %>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @friend.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @friend.title %>
</p>

<p>
  <strong>Nickname:</strong>
  <%= @friend.nickname %>
</p>

<p>
  <strong>All:</strong>
  <%= @friend.all %>
</p>

<p>
  <strong>Family:</strong>
  <%= @friend.family %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friend.friend %>
</p>

<p>
  <strong>Work:</strong>
  <%= @friend.work %>
</p>

<p>
  <strong>School:</strong>
  <%= @friend.school %>
</p>

<p>
  <strong>Personal:</strong>
  <%= @friend.personal %>
</p>

<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path %>

app/views/list_permissions/_form.html.erb
<%= form_for(@list_permission) do |f| %>
  <% if @list_permission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list_permission.errors.count, "error") %> prohibited this list_permission from being saved:</h2>

      <ul>
      <% @list_permission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :listId %><br>
    <%= f.number_field :listId %>
  </div>
  <div class="field">
    <%= f.label :UserId %><br>
    <%= f.number_field :UserId %>
  </div>
  <div class="field">
    <%= f.label :permissionType %><br>
    <%= f.text_field :permissionType %>
  </div>
  <div class="field">
    <%= f.label :shareStatus %><br>
    <%= f.text_field :shareStatus %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/list_permissions/edit.html.erb
<h1>Editing list_permission</h1>

<%= render 'form' %>

<%= link_to 'Show', @list_permission %> |
<%= link_to 'Back', list_permissions_path %>

app/views/list_permissions/index.html.erb
<h1>Listing list_permissions</h1>

<table>
  <thead>
    <tr>
      <th>Listid</th>
      <th>Userid</th>
      <th>Permissiontype</th>
      <th>Sharestatus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @list_permissions.each do |list_permission| %>
      <tr>
        <td><%= list_permission.listId %></td>
        <td><%= list_permission.UserId %></td>
        <td><%= list_permission.permissionType %></td>
        <td><%= list_permission.shareStatus %></td>
        <td><%= link_to 'Show', list_permission %></td>
        <td><%= link_to 'Edit', edit_list_permission_path(list_permission) %></td>
        <td><%= link_to 'Destroy', list_permission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List permission', new_list_permission_path %>

app/views/list_permissions/new.html.erb
<h1>New list_permission</h1>

<%= render 'form' %>

<%= link_to 'Back', list_permissions_path %>

app/views/list_permissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Listid:</strong>
  <%= @list_permission.listId %>
</p>

<p>
  <strong>Userid:</strong>
  <%= @list_permission.UserId %>
</p>

<p>
  <strong>Permissiontype:</strong>
  <%= @list_permission.permissionType %>
</p>

<p>
  <strong>Sharestatus:</strong>
  <%= @list_permission.shareStatus %>
</p>

<%= link_to 'Edit', edit_list_permission_path(@list_permission) %> |
<%= link_to 'Back', list_permissions_path %>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :creatorUserID %><br>
    <%= f.number_field :creatorUserID %>
  </div>
  <div class="field">
    <%= f.label :numShared %><br>
    <%= f.number_field :numShared %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Listing lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Creatoruserid</th>
      <th>Numshared</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <td><%= list.creatorUserID %></td>
        <td><%= list.numShared %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<p>
  <strong>Creatoruserid:</strong>
  <%= @list.creatorUserID %>
</p>

<p>
  <strong>Numshared:</strong>
  <%= @list.numShared %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :hidden %><br>
    <%= f.check_box :hidden %>
  </div>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
  <div class="field">
    <%= f.label :whoCompleted %><br>
    <%= f.number_field :whoCompleted %>
  </div>
  <div class="field">
    <%= f.label :dateCompleted %><br>
    <%= f.datetime_select :dateCompleted %>
  </div>
  <div class="field">
    <%= f.label :whoCreated %><br>
    <%= f.number_field :whoCreated %>
  </div>
  <div class="field">
    <%= f.label :createPermission %><br>
    <%= f.text_field :createPermission %>
  </div>
  <div class="field">
    <%= f.label :whoHid %><br>
    <%= f.number_field :whoHid %>
  </div>
  <div class="field">
    <%= f.label :dateHidden %><br>
    <%= f.datetime_select :dateHidden %>
  </div>
  <div class="field">
    <%= f.label :whoEdit %><br>
    <%= f.number_field :whoEdit %>
  </div>
  <div class="field">
    <%= f.label :lastEdit %><br>
    <%= f.datetime_select :lastEdit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Hidden</th>
      <th>Completed</th>
      <th>Whocompleted</th>
      <th>Datecompleted</th>
      <th>Whocreated</th>
      <th>Createpermission</th>
      <th>Whohid</th>
      <th>Datehidden</th>
      <th>Whoedit</th>
      <th>Lastedit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.hidden %></td>
        <td><%= task.completed %></td>
        <td><%= task.whoCompleted %></td>
        <td><%= task.dateCompleted %></td>
        <td><%= task.whoCreated %></td>
        <td><%= task.createPermission %></td>
        <td><%= task.whoHid %></td>
        <td><%= task.dateHidden %></td>
        <td><%= task.whoEdit %></td>
        <td><%= task.lastEdit %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Hidden:</strong>
  <%= @task.hidden %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @task.completed %>
</p>

<p>
  <strong>Whocompleted:</strong>
  <%= @task.whoCompleted %>
</p>

<p>
  <strong>Datecompleted:</strong>
  <%= @task.dateCompleted %>
</p>

<p>
  <strong>Whocreated:</strong>
  <%= @task.whoCreated %>
</p>

<p>
  <strong>Createpermission:</strong>
  <%= @task.createPermission %>
</p>

<p>
  <strong>Whohid:</strong>
  <%= @task.whoHid %>
</p>

<p>
  <strong>Datehidden:</strong>
  <%= @task.dateHidden %>
</p>

<p>
  <strong>Whoedit:</strong>
  <%= @task.whoEdit %>
</p>

<p>
  <strong>Lastedit:</strong>
  <%= @task.lastEdit %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :inviteCode %><br>
    <%= f.text_field :inviteCode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table border="1px" width="100%">
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Invitecode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.title %></td>
        <td><%= user.inviteCode %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @user.title %>
</p>

<p>
  <strong>Invitecode:</strong>
  <%= @user.inviteCode %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>